version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: datamanagement
    ports:
      - "27017:27017"
    volumes:  
      - mongo-data:/data/db

  read-service:
    build: ./read-service
    ports:
      - "3003:3003"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=datamanagement
    depends_on:
      - mongodb
    volumes:
      - ./read-service:/app
      - /app/node_modules

  create-service:
    build: ./create-service
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=datamanagement
    depends_on:
      - mongodb
    volumes:
      - ./create-service:/app
      - /app/node_modules

  delete-service:
    build: ./delete-service
    ports:
      - "3002:3002"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=datamanagement
    depends_on:
      - mongodb
    volumes:
      - ./delete-service:/app
      - /app/node_modules

  update-service:
    build: ./update-service
    ports:
      - "3004:3004"
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=datamanagement
    depends_on:
      - mongodb
    volumes:
      - ./update-service:/app
      - /app/node_modules

volumes:
  mongo-data:
